### PR TITLE
fixed the the pet name padding so the pet name that goes to 2 lines d…

### PR DESCRIPTION
**Pull request by jess-nash**
…oesnt go udner the buttons div

### CODE REVIEW

**Comment by noliver-ykc** [comment]
can you fix your conflicts first? @jess-nash

**Review by noliver-ykc — CHANGES_REQUESTED** [review]
merge conflicts

**Comment by jess-nash** [comment]
> merge conflicts

@noliver-ykc It was because of the end div I forgot then add
fixed~!

**Review by noliver-ykc — APPROVED** [review]
LGTM

**Pull request merged**
